# Generated by Django 3.0 on 2019-12-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('storage', models.CharField(max_length=200)),
                ('screen_size', models.CharField(max_length=200)),
                ('OS', models.CharField(max_length=200)),
                ('RAM', models.CharField(max_length=200)),
                ('Processor', models.CharField(max_length=200)),
                ('Warranty', models.CharField(max_length=200)),
                ('Price', models.FloatField(null=True)),
            ],
        ),
    ]
