# Generated by Django 3.0 on 2019-12-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20191216_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
